/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.BalanceHistoryWindow
import xyz.hisname.openmeter.models.Period

class BalanceHistoryWindowTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of BalanceHistoryWindow
        //val modelInstance = BalanceHistoryWindow()

        // to test the property `period`
        should("test period") {
            // uncomment below to test the property
            //modelInstance.period shouldBe ("TODO")
        }

        // to test the property `usage` - The total usage of the feature in the period. 
        should("test usage") {
            // uncomment below to test the property
            //modelInstance.usage shouldBe ("TODO")
        }

        // to test the property `balanceAtStart` - The entitlement balance at the start of the period. 
        should("test balanceAtStart") {
            // uncomment below to test the property
            //modelInstance.balanceAtStart shouldBe ("TODO")
        }

    }
}
