/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.ConflictProblemExtensions

class ConflictProblemExtensionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ConflictProblemExtensions
        //val modelInstance = ConflictProblemExtensions()

        // to test the property `conflictingEntityId` - The id of the conflicting entity.
        should("test conflictingEntityId") {
            // uncomment below to test the property
            //modelInstance.conflictingEntityId shouldBe ("TODO")
        }

    }
}
