/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.EntitlementStatic
import xyz.hisname.openmeter.models.Period
import xyz.hisname.openmeter.models.RecurringPeriod

class EntitlementStaticTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EntitlementStatic
        //val modelInstance = EntitlementStatic()

        // to test the property `featureKey` - The feature the subject is entitled to use. Either featureKey or featureId is required. 
        should("test featureKey") {
            // uncomment below to test the property
            //modelInstance.featureKey shouldBe ("TODO")
        }

        // to test the property `featureId` - The feature the subject is entitled to use. Either featureKey or featureId is required. 
        should("test featureId") {
            // uncomment below to test the property
            //modelInstance.featureId shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `config` - The JSON parsable config of the entitlement. This value is also returned when checking entitlement access and it is useful for configuring fine-grained access settings to the feature, implemented in your own system. Has to be an object. 
        should("test config") {
            // uncomment below to test the property
            //modelInstance.config shouldBe ("TODO")
        }

        // to test the property `id` - Readonly unique ULID identifier. 
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `createdAt` - The date and time the resource was created.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - The date and time the resource was last updated. The initial value is the same as createdAt.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `subjectKey` - The identifier key unique to the subject
        should("test subjectKey") {
            // uncomment below to test the property
            //modelInstance.subjectKey shouldBe ("TODO")
        }

        // to test the property `metadata` - Additional metadata for the feature. 
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `usagePeriod`
        should("test usagePeriod") {
            // uncomment below to test the property
            //modelInstance.usagePeriod shouldBe ("TODO")
        }

        // to test the property `deletedAt` - The date and time the resource was deleted.
        should("test deletedAt") {
            // uncomment below to test the property
            //modelInstance.deletedAt shouldBe ("TODO")
        }

        // to test the property `currentUsagePeriod`
        should("test currentUsagePeriod") {
            // uncomment below to test the property
            //modelInstance.currentUsagePeriod shouldBe ("TODO")
        }

    }
}
