/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.EntitlementCreateSharedFields
import xyz.hisname.openmeter.models.RecurringPeriodCreateInput

class EntitlementCreateSharedFieldsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EntitlementCreateSharedFields
        //val modelInstance = EntitlementCreateSharedFields()

        // to test the property `featureKey` - The feature the subject is entitled to use. Either featureKey or featureId is required. 
        should("test featureKey") {
            // uncomment below to test the property
            //modelInstance.featureKey shouldBe ("TODO")
        }

        // to test the property `featureId` - The feature the subject is entitled to use. Either featureKey or featureId is required. 
        should("test featureId") {
            // uncomment below to test the property
            //modelInstance.featureId shouldBe ("TODO")
        }

        // to test the property `metadata` - Additional metadata for the feature. 
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `usagePeriod`
        should("test usagePeriod") {
            // uncomment below to test the property
            //modelInstance.usagePeriod shouldBe ("TODO")
        }

    }
}
