/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.EntitlementCreateInputs
import xyz.hisname.openmeter.models.EntitlementBooleanCreateInputs
import xyz.hisname.openmeter.models.EntitlementMeteredCreateInputs
import xyz.hisname.openmeter.models.EntitlementStaticCreateInputs
import xyz.hisname.openmeter.models.MeasureUsageFrom
import xyz.hisname.openmeter.models.RecurringPeriodCreateInput

class EntitlementCreateInputsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EntitlementCreateInputs
        //val modelInstance = EntitlementCreateInputs()

        // to test the property `usagePeriod`
        should("test usagePeriod") {
            // uncomment below to test the property
            //modelInstance.usagePeriod shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `config` - The JSON parsable config of the entitlement. This value is also returned when checking entitlement access and it is useful for configuring fine-grained access settings to the feature, implemented in your own system. Has to be an object. 
        should("test config") {
            // uncomment below to test the property
            //modelInstance.config shouldBe ("TODO")
        }

        // to test the property `featureKey` - The feature the subject is entitled to use. Either featureKey or featureId is required. 
        should("test featureKey") {
            // uncomment below to test the property
            //modelInstance.featureKey shouldBe ("TODO")
        }

        // to test the property `featureId` - The feature the subject is entitled to use. Either featureKey or featureId is required. 
        should("test featureId") {
            // uncomment below to test the property
            //modelInstance.featureId shouldBe ("TODO")
        }

        // to test the property `metadata` - Additional metadata for the feature. 
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `isSoftLimit` - If softLimit=true the subject can use the feature even if the entitlement is exhausted, hasAccess will always be true. 
        should("test isSoftLimit") {
            // uncomment below to test the property
            //modelInstance.isSoftLimit shouldBe ("TODO")
        }

        // to test the property `isUnlimited` - Deprecated, ignored by the backend. Please use isSoftLimit instead; this field will be removed in the future. 
        should("test isUnlimited") {
            // uncomment below to test the property
            //modelInstance.isUnlimited shouldBe ("TODO")
        }

        // to test the property `measureUsageFrom`
        should("test measureUsageFrom") {
            // uncomment below to test the property
            //modelInstance.measureUsageFrom shouldBe ("TODO")
        }

        // to test the property `issueAfterReset` - You can grant usage automatically alongside the entitlement, the example scenario would be creating a starting balance. If an amount is specified here, a grant will be created alongside the entitlement with the specified amount. That grant will have it's rollover settings configured in a way that after each reset operation, the balance will return the original amount specified here.  Manually creating such a grant would mean having the \"amount\", \"minRolloverAmount\", and \"maxRolloverAmount\" fields all be the same. 
        should("test issueAfterReset") {
            // uncomment below to test the property
            //modelInstance.issueAfterReset shouldBe ("TODO")
        }

        // to test the property `issueAfterResetPriority` - Defines the grant priority for the default grant. If provided, issueAfterReset must have a value. 
        should("test issueAfterResetPriority") {
            // uncomment below to test the property
            //modelInstance.issueAfterResetPriority shouldBe ("TODO")
        }

        // to test the property `preserveOverageAtReset` - If true, the overage is preserved at reset. If false, the usage is forgiven. 
        should("test preserveOverageAtReset") {
            // uncomment below to test the property
            //modelInstance.preserveOverageAtReset shouldBe ("TODO")
        }

    }
}
