/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.EntitlementValue

class EntitlementValueTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EntitlementValue
        //val modelInstance = EntitlementValue()

        // to test the property `hasAccess` - Whether the subject has access to the feature. Shared accross all entitlement types. 
        should("test hasAccess") {
            // uncomment below to test the property
            //modelInstance.hasAccess shouldBe ("TODO")
        }

        // to test the property `balance` - Only available for metered entitlements. Metered entitlements are built around a balance calculation where feature usage is deducted from the issued grants. Balance represents the remaining balance of the entitlement, it's value never turns negative. 
        should("test balance") {
            // uncomment below to test the property
            //modelInstance.balance shouldBe ("TODO")
        }

        // to test the property `usage` - Only available for metered entitlements. Returns the total feature usage in the current period. 
        should("test usage") {
            // uncomment below to test the property
            //modelInstance.usage shouldBe ("TODO")
        }

        // to test the property `overage` - Only available for metered entitlements. Overage represents the usage that wasn't covered by grants, e.g. if the subject had a total feature usage of 100 in the period but they were only granted 80, there would be 20 overage. 
        should("test overage") {
            // uncomment below to test the property
            //modelInstance.overage shouldBe ("TODO")
        }

        // to test the property `config` - Only available for static entitlements. The JSON parsable config of the entitlement. 
        should("test config") {
            // uncomment below to test the property
            //modelInstance.config shouldBe ("TODO")
        }

    }
}
