/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.EntitlementMeteredCalculatedFields
import xyz.hisname.openmeter.models.Period

class EntitlementMeteredCalculatedFieldsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EntitlementMeteredCalculatedFields
        //val modelInstance = EntitlementMeteredCalculatedFields()

        // to test the property `lastReset` - The last time a reset happened. 
        should("test lastReset") {
            // uncomment below to test the property
            //modelInstance.lastReset shouldBe ("TODO")
        }

        // to test the property `currentUsagePeriod`
        should("test currentUsagePeriod") {
            // uncomment below to test the property
            //modelInstance.currentUsagePeriod shouldBe ("TODO")
        }

        // to test the property `measureUsageFrom` - The time from which usage is measured. If not specified on creation, defaults to the entitlement creation time. 
        should("test measureUsageFrom") {
            // uncomment below to test the property
            //modelInstance.measureUsageFrom shouldBe ("TODO")
        }

    }
}
