/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.ExpirationPeriod

class ExpirationPeriodTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExpirationPeriod
        //val modelInstance = ExpirationPeriod()

        // to test the property `duration` - The expiration period duration like month. 
        should("test duration") {
            // uncomment below to test the property
            //modelInstance.duration shouldBe ("TODO")
        }

        // to test the property `count` - The expiration period count like 12 months. 
        should("test count") {
            // uncomment below to test the property
            //modelInstance.count shouldBe ("TODO")
        }

    }
}
