/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.GetEntitlementById200Response
import xyz.hisname.openmeter.models.Entitlement
import xyz.hisname.openmeter.models.Period
import xyz.hisname.openmeter.models.RecurringPeriod

class GetEntitlementById200ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetEntitlementById200Response
        //val modelInstance = GetEntitlementById200Response()

        // to test the property `lastReset` - The last time usage was reset.
        should("test lastReset") {
            // uncomment below to test the property
            //modelInstance.lastReset shouldBe ("TODO")
        }

    }
}
