/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.GrantBurnDownHistorySegment
import xyz.hisname.openmeter.models.GrantUsageRecord
import xyz.hisname.openmeter.models.Period

class GrantBurnDownHistorySegmentTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GrantBurnDownHistorySegment
        //val modelInstance = GrantBurnDownHistorySegment()

        // to test the property `period`
        should("test period") {
            // uncomment below to test the property
            //modelInstance.period shouldBe ("TODO")
        }

        // to test the property `usage` - The usage of the grant in the period. 
        should("test usage") {
            // uncomment below to test the property
            //modelInstance.usage shouldBe ("TODO")
        }

        // to test the property `overage` - Overuse that wasn't covered by grants. 
        should("test overage") {
            // uncomment below to test the property
            //modelInstance.overage shouldBe ("TODO")
        }

        // to test the property `balanceAtStart` - The entitlement balance at the start of the period. 
        should("test balanceAtStart") {
            // uncomment below to test the property
            //modelInstance.balanceAtStart shouldBe ("TODO")
        }

        // to test the property `grantBalancesAtStart` - The balance breakdown of each active grant at the start of the period: GrantID: Balance 
        should("test grantBalancesAtStart") {
            // uncomment below to test the property
            //modelInstance.grantBalancesAtStart shouldBe ("TODO")
        }

        // to test the property `balanceAtEnd` - The entitlement balance at the end of the period. 
        should("test balanceAtEnd") {
            // uncomment below to test the property
            //modelInstance.balanceAtEnd shouldBe ("TODO")
        }

        // to test the property `grantBalancesAtEnd` - The balance breakdown of each active grant at the start of the period: GrantID: Balance 
        should("test grantBalancesAtEnd") {
            // uncomment below to test the property
            //modelInstance.grantBalancesAtEnd shouldBe ("TODO")
        }

        // to test the property `grantUsages` - Which grants were actually burnt down in the period and by what amount. 
        should("test grantUsages") {
            // uncomment below to test the property
            //modelInstance.grantUsages shouldBe ("TODO")
        }

    }
}
