/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.GrantUsageRecord

class GrantUsageRecordTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GrantUsageRecord
        //val modelInstance = GrantUsageRecord()

        // to test the property `grantId` - The id of the grant. 
        should("test grantId") {
            // uncomment below to test the property
            //modelInstance.grantId shouldBe ("TODO")
        }

        // to test the property `usage` - The usage of the grant. 
        should("test usage") {
            // uncomment below to test the property
            //modelInstance.usage shouldBe ("TODO")
        }

    }
}
