/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.IngestedEvent
import xyz.hisname.openmeter.models.Event

class IngestedEventTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of IngestedEvent
        //val modelInstance = IngestedEvent()

        // to test the property `event`
        should("test event") {
            // uncomment below to test the property
            //modelInstance.event shouldBe ("TODO")
        }

        // to test the property `validationError`
        should("test validationError") {
            // uncomment below to test the property
            //modelInstance.validationError shouldBe ("TODO")
        }

    }
}
