/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.InvalidatePortalTokensRequest

class InvalidatePortalTokensRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InvalidatePortalTokensRequest
        //val modelInstance = InvalidatePortalTokensRequest()

        // to test the property `id` - Invalidate a portal token by ID.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `subject` - Invalidate all portal tokens for a subject.
        should("test subject") {
            // uncomment below to test the property
            //modelInstance.subject shouldBe ("TODO")
        }

    }
}
