/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.MeterQueryRow

class MeterQueryRowTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MeterQueryRow
        //val modelInstance = MeterQueryRow()

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `windowStart`
        should("test windowStart") {
            // uncomment below to test the property
            //modelInstance.windowStart shouldBe ("TODO")
        }

        // to test the property `windowEnd`
        should("test windowEnd") {
            // uncomment below to test the property
            //modelInstance.windowEnd shouldBe ("TODO")
        }

        // to test the property `subject` - The subject of the meter value.
        should("test subject") {
            // uncomment below to test the property
            //modelInstance.subject shouldBe ("TODO")
        }

        // to test the property `groupBy`
        should("test groupBy") {
            // uncomment below to test the property
            //modelInstance.groupBy shouldBe ("TODO")
        }

    }
}
