/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.MeterQueryResult
import xyz.hisname.openmeter.models.MeterQueryRow
import xyz.hisname.openmeter.models.WindowSize

class MeterQueryResultTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MeterQueryResult
        //val modelInstance = MeterQueryResult()

        // to test the property ``data``
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `from`
        should("test from") {
            // uncomment below to test the property
            //modelInstance.from shouldBe ("TODO")
        }

        // to test the property `to`
        should("test to") {
            // uncomment below to test the property
            //modelInstance.to shouldBe ("TODO")
        }

        // to test the property `windowSize`
        should("test windowSize") {
            // uncomment below to test the property
            //modelInstance.windowSize shouldBe ("TODO")
        }

    }
}
