/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.NotificationChannelWebhookCreateRequest
import xyz.hisname.openmeter.models.NotificationChannelType

class NotificationChannelWebhookCreateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationChannelWebhookCreateRequest
        //val modelInstance = NotificationChannelWebhookCreateRequest()

        // to test the property `name` - User friendly name of the channel.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `url` - Webhook URL where the notification is sent.
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `disabled` - Whether the channel is disabled or not.
        should("test disabled") {
            // uncomment below to test the property
            //modelInstance.disabled shouldBe ("TODO")
        }

        // to test the property `customHeaders` - Custom HTTP headers sent as part of the webhook request.
        should("test customHeaders") {
            // uncomment below to test the property
            //modelInstance.customHeaders shouldBe ("TODO")
        }

        // to test the property `signingSecret` - Signing secret used for webhook request validation on the receiving end. Automatically generated if not provided.  Format: `base64` encoded random bytes optionally prefixed with `whsec_`. Recommended size: 24 
        should("test signingSecret") {
            // uncomment below to test the property
            //modelInstance.signingSecret shouldBe ("TODO")
        }

    }
}
