/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.NotificationChannelWebhook
import xyz.hisname.openmeter.models.NotificationChannelType

class NotificationChannelWebhookTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationChannelWebhook
        //val modelInstance = NotificationChannelWebhook()

        // to test the property `id` - A unique identifier for the notification channel.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `name` - User friendly name of the channel.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `createdAt` - Timestamp when the channel was created.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - Timestamp when the channel was modified.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `disabled` - Whether the channel is disabled or not.
        should("test disabled") {
            // uncomment below to test the property
            //modelInstance.disabled shouldBe ("TODO")
        }

        // to test the property `url` - Webhook URL where the notification is sent.
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

        // to test the property `signingSecret` - Signing secret used for webhook request validation on the receiving end.  Format: `base64` encoded random bytes optionally prefixed with `whsec_`. Recommended size: 24 
        should("test signingSecret") {
            // uncomment below to test the property
            //modelInstance.signingSecret shouldBe ("TODO")
        }

        // to test the property `deletedAt` - Timestamp when the channel was deleted.
        should("test deletedAt") {
            // uncomment below to test the property
            //modelInstance.deletedAt shouldBe ("TODO")
        }

        // to test the property `customHeaders` - Custom HTTP headers sent as part of the webhook request.
        should("test customHeaders") {
            // uncomment below to test the property
            //modelInstance.customHeaders shouldBe ("TODO")
        }

    }
}
