/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.NotificationEventBalanceThresholdPayloadAllOfData
import xyz.hisname.openmeter.models.EntitlementMetered
import xyz.hisname.openmeter.models.EntitlementValue
import xyz.hisname.openmeter.models.Feature
import xyz.hisname.openmeter.models.NotificationRuleBalanceThresholdValue
import xyz.hisname.openmeter.models.Subject

class NotificationEventBalanceThresholdPayloadAllOfDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationEventBalanceThresholdPayloadAllOfData
        //val modelInstance = NotificationEventBalanceThresholdPayloadAllOfData()

        // to test the property `entitlement`
        should("test entitlement") {
            // uncomment below to test the property
            //modelInstance.entitlement shouldBe ("TODO")
        }

        // to test the property `feature`
        should("test feature") {
            // uncomment below to test the property
            //modelInstance.feature shouldBe ("TODO")
        }

        // to test the property `subject`
        should("test subject") {
            // uncomment below to test the property
            //modelInstance.subject shouldBe ("TODO")
        }

        // to test the property ``value``
        should("test `value`") {
            // uncomment below to test the property
            //modelInstance.`value` shouldBe ("TODO")
        }

        // to test the property `threshold`
        should("test threshold") {
            // uncomment below to test the property
            //modelInstance.threshold shouldBe ("TODO")
        }

    }
}
