/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.NotificationChannelCommonCreateRequest
import xyz.hisname.openmeter.models.NotificationChannelType

class NotificationChannelCommonCreateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationChannelCommonCreateRequest
        //val modelInstance = NotificationChannelCommonCreateRequest()

        // to test the property `name` - User friendly name of the channel.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `disabled` - Whether the channel is disabled or not.
        should("test disabled") {
            // uncomment below to test the property
            //modelInstance.disabled shouldBe ("TODO")
        }

    }
}
