/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.NotificationRuleCommon
import xyz.hisname.openmeter.models.NotificationChannelMeta
import xyz.hisname.openmeter.models.NotificationEventType

class NotificationRuleCommonTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationRuleCommon
        //val modelInstance = NotificationRuleCommon()

        // to test the property `id` - A unique identifier for the notification rule.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `name` - The user friendly name of the notification rule.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `channels` - List of notification channels the rule applies to.
        should("test channels") {
            // uncomment below to test the property
            //modelInstance.channels shouldBe ("TODO")
        }

        // to test the property `createdAt` - Timestamp when the rule was created.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `updatedAt` - Timestamp when the rule was modified.
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

        // to test the property `disabled` - Whether the rule is disabled or not.
        should("test disabled") {
            // uncomment below to test the property
            //modelInstance.disabled shouldBe ("TODO")
        }

        // to test the property `deletedAt` - Timestamp when the channel was deleted.
        should("test deletedAt") {
            // uncomment below to test the property
            //modelInstance.deletedAt shouldBe ("TODO")
        }

    }
}
