/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.NotificationEventCreateRequest
import xyz.hisname.openmeter.models.NotificationEventPayload
import xyz.hisname.openmeter.models.NotificationEventType

class NotificationEventCreateRequestTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationEventCreateRequest
        //val modelInstance = NotificationEventCreateRequest()

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `payload`
        should("test payload") {
            // uncomment below to test the property
            //modelInstance.payload shouldBe ("TODO")
        }

        // to test the property `ruleId`
        should("test ruleId") {
            // uncomment below to test the property
            //modelInstance.ruleId shouldBe ("TODO")
        }

    }
}
