/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.Problem

class ProblemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Problem
        //val modelInstance = Problem()

        // to test the property `type` - Type contains a URI that identifies the problem type.
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `title` - A a short, human-readable summary of the problem type.
        should("test title") {
            // uncomment below to test the property
            //modelInstance.title shouldBe ("TODO")
        }

        // to test the property `status` - The HTTP status code generated by the origin server for this occurrence of the problem.
        should("test status") {
            // uncomment below to test the property
            //modelInstance.status shouldBe ("TODO")
        }

        // to test the property `detail` - A human-readable explanation specific to this occurrence of the problem.
        should("test detail") {
            // uncomment below to test the property
            //modelInstance.detail shouldBe ("TODO")
        }

        // to test the property `instance` - A URI reference that identifies the specific occurrence of the problem.
        should("test instance") {
            // uncomment below to test the property
            //modelInstance.instance shouldBe ("TODO")
        }

    }
}
