/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.RecurringPeriod
import xyz.hisname.openmeter.models.RecurringPeriodEnum

class RecurringPeriodTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RecurringPeriod
        //val modelInstance = RecurringPeriod()

        // to test the property `interval`
        should("test interval") {
            // uncomment below to test the property
            //modelInstance.interval shouldBe ("TODO")
        }

        // to test the property `anchor` - An arbitrary anchor to base the recurring period on. 
        should("test anchor") {
            // uncomment below to test the property
            //modelInstance.anchor shouldBe ("TODO")
        }

    }
}
