/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.Subject

class SubjectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Subject
        //val modelInstance = Subject()

        // to test the property `key`
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `displayName`
        should("test displayName") {
            // uncomment below to test the property
            //modelInstance.displayName shouldBe ("TODO")
        }

        // to test the property `metadata`
        should("test metadata") {
            // uncomment below to test the property
            //modelInstance.metadata shouldBe ("TODO")
        }

        // to test the property `currentPeriodStart`
        should("test currentPeriodStart") {
            // uncomment below to test the property
            //modelInstance.currentPeriodStart shouldBe ("TODO")
        }

        // to test the property `currentPeriodEnd`
        should("test currentPeriodEnd") {
            // uncomment below to test the property
            //modelInstance.currentPeriodEnd shouldBe ("TODO")
        }

        // to test the property `stripeCustomerId`
        should("test stripeCustomerId") {
            // uncomment below to test the property
            //modelInstance.stripeCustomerId shouldBe ("TODO")
        }

    }
}
