/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.models.TestNotificationRule201Response
import xyz.hisname.openmeter.models.NotificationEvent
import xyz.hisname.openmeter.models.NotificationEventDeliveryStatus
import xyz.hisname.openmeter.models.NotificationEventPayload
import xyz.hisname.openmeter.models.NotificationEventType
import xyz.hisname.openmeter.models.NotificationRule

class TestNotificationRule201ResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TestNotificationRule201Response
        //val modelInstance = TestNotificationRule201Response()

        // to test the property `id` - A unique identifier for the notification event.
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

        // to test the property `createdAt` - Timestamp when the notification event was created.
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `rule`
        should("test rule") {
            // uncomment below to test the property
            //modelInstance.rule shouldBe ("TODO")
        }

        // to test the property `deliveryStatus` - The delivery status of the notification event.
        should("test deliveryStatus") {
            // uncomment below to test the property
            //modelInstance.deliveryStatus shouldBe ("TODO")
        }

        // to test the property `payload`
        should("test payload") {
            // uncomment below to test the property
            //modelInstance.payload shouldBe ("TODO")
        }

        // to test the property `annotations` - List of annotations managed by the system. 
        should("test annotations") {
            // uncomment below to test the property
            //modelInstance.annotations shouldBe ("TODO")
        }

    }
}
