/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.apis.DebugApi
import xyz.hisname.openmeter.models.Problem

class DebugApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DebugApi
        //val apiInstance = DebugApi()

        // to test getDebugMetrics
        should("test getDebugMetrics") {
            // uncomment below to test getDebugMetrics
            //val result : kotlin.String = apiInstance.getDebugMetrics()
            //result shouldBe ("TODO")
        }

    }
}
