/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import xyz.hisname.openmeter.apis.NotificationsExperimentalApi
import xyz.hisname.openmeter.models.Problem
import xyz.hisname.openmeter.models.SvixOperationalWebhookRequest

class NotificationsExperimentalApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NotificationsExperimentalApi
        //val apiInstance = NotificationsExperimentalApi()

        // to test receiveSvixOperationalEvent
        should("test receiveSvixOperationalEvent") {
            // uncomment below to test receiveSvixOperationalEvent
            //val svixOperationalWebhookRequest : SvixOperationalWebhookRequest =  // SvixOperationalWebhookRequest | The operational event.
            //apiInstance.receiveSvixOperationalEvent(svixOperationalWebhookRequest)
        }

    }
}
