/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.Period

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Windowed usage and balance information. 
 *
 * @param period 
 * @param usage The total usage of the feature in the period. 
 * @param balanceAtStart The entitlement balance at the start of the period. 
 */
@Serializable

data class BalanceHistoryWindow (

    @SerialName(value = "period") val period: Period? = null,

    /* The total usage of the feature in the period.  */
    @SerialName(value = "usage") val usage: kotlin.Double? = null,

    /* The entitlement balance at the start of the period.  */
    @SerialName(value = "balanceAtStart") val balanceAtStart: kotlin.Double? = null

) {


}

