/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.RecurringPeriodCreateInput

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type 
 * @param config The JSON parsable config of the entitlement. This value is also returned when checking entitlement access and it is useful for configuring fine-grained access settings to the feature, implemented in your own system. Has to be an object. 
 * @param featureKey The feature the subject is entitled to use. Either featureKey or featureId is required. 
 * @param featureId The feature the subject is entitled to use. Either featureKey or featureId is required. 
 * @param metadata Additional metadata for the feature. 
 * @param usagePeriod 
 */
@Serializable

data class EntitlementStaticCreateInputs (

    @SerialName(value = "type") @Required val type: EntitlementStaticCreateInputs.Type,

    /* The JSON parsable config of the entitlement. This value is also returned when checking entitlement access and it is useful for configuring fine-grained access settings to the feature, implemented in your own system. Has to be an object.  */
    @SerialName(value = "config") @Required val config: kotlin.String,

    /* The feature the subject is entitled to use. Either featureKey or featureId is required.  */
    @SerialName(value = "featureKey") val featureKey: kotlin.String? = null,

    /* The feature the subject is entitled to use. Either featureKey or featureId is required.  */
    @SerialName(value = "featureId") val featureId: kotlin.String? = null,

    /* Additional metadata for the feature.  */
    @SerialName(value = "metadata") val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "usagePeriod") val usagePeriod: RecurringPeriodCreateInput? = null

) {

    /**
     * 
     *
     * Values: static
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "static") static("static");
    }

}

