/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.Period

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Calculated fields for a metered entitlement.
 *
 * @param lastReset The last time a reset happened. 
 * @param currentUsagePeriod 
 * @param measureUsageFrom The time from which usage is measured. If not specified on creation, defaults to the entitlement creation time. 
 */
@Serializable

data class EntitlementMeteredCalculatedFields (

    /* The last time a reset happened.  */
    @SerialName(value = "lastReset") @Required val lastReset: kotlinx.datetime.Instant,

    @SerialName(value = "currentUsagePeriod") @Required val currentUsagePeriod: Period,

    /* The time from which usage is measured. If not specified on creation, defaults to the entitlement creation time.  */
    @SerialName(value = "measureUsageFrom") @Required val measureUsageFrom: kotlinx.datetime.Instant

) {


}

