/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.RecurringPeriodCreateInput

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param featureKey The feature the subject is entitled to use. Either featureKey or featureId is required. 
 * @param featureId The feature the subject is entitled to use. Either featureKey or featureId is required. 
 * @param metadata Additional metadata for the feature. 
 * @param usagePeriod 
 */
@Serializable

data class EntitlementCreateSharedFields (

    /* The feature the subject is entitled to use. Either featureKey or featureId is required.  */
    @SerialName(value = "featureKey") val featureKey: kotlin.String? = null,

    /* The feature the subject is entitled to use. Either featureKey or featureId is required.  */
    @SerialName(value = "featureId") val featureId: kotlin.String? = null,

    /* Additional metadata for the feature.  */
    @SerialName(value = "metadata") val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "usagePeriod") val usagePeriod: RecurringPeriodCreateInput? = null

) {


}

