/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Expiration period of a grant. 
 *
 * @param duration The expiration period duration like month. 
 * @param count The expiration period count like 12 months. 
 */
@Serializable

data class ExpirationPeriod (

    /* The expiration period duration like month.  */
    @SerialName(value = "duration") @Required val duration: ExpirationPeriod.Duration,

    /* The expiration period count like 12 months.  */
    @SerialName(value = "count") @Required val count: kotlin.Int

) {

    /**
     * The expiration period duration like month. 
     *
     * Values: HOUR,DAY,WEEK,MONTH,YEAR
     */
    @Serializable
    enum class Duration(val value: kotlin.String) {
        @SerialName(value = "HOUR") HOUR("HOUR"),
        @SerialName(value = "DAY") DAY("DAY"),
        @SerialName(value = "WEEK") WEEK("WEEK"),
        @SerialName(value = "MONTH") MONTH("MONTH"),
        @SerialName(value = "YEAR") YEAR("YEAR");
    }

}

