/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Limited representation of a feature resource which includes only its unique identifiers (id, key). 
 *
 * @param id A unique identifier for the notification rule.
 * @param key The key is an immutable unique identifier of the feature used throughout the API, for example when interacting with a subject's entitlements. 
 */
@Serializable

data class FeatureMeta (

    /* A unique identifier for the notification rule. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The key is an immutable unique identifier of the feature used throughout the API, for example when interacting with a subject's entitlements.  */
    @SerialName(value = "key") @Required val key: kotlin.String

) {


}

