/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param featureKey The feature the subject is entitled to use. Either featureKey or featureId is required. 
 * @param featureId The feature the subject is entitled to use. Either featureKey or featureId is required. 
 * @param usagePeriod 
 * @param type
 * @param measureUsageFrom The time from which usage is measured. If not specified on creation, defaults to the entitlement creation time.
 * @param currentUsagePeriod 
 * @param id Readonly unique ULID identifier. 
 * @param createdAt The date and time the resource was created.
 * @param updatedAt The date and time the resource was last updated. The initial value is the same as createdAt.
 * @param subjectKey The identifier key unique to the subject
 * @param config The JSON parsable config of the entitlement. This value is also returned when checking entitlement access and it is useful for configuring fine-grained access settings to the feature, implemented in your own system. Has to be an object. 
 * @param metadata Additional metadata for the feature. 
 * @param isSoftLimit If softLimit=true the subject can use the feature even if the entitlement is exhausted, hasAccess will always be true. 
 * @param isUnlimited Deprecated, ignored by the backend. Please use isSoftLimit instead; this field will be removed in the future. 
 * @param issueAfterReset You can grant usage automatically alongside the entitlement, the example scenario would be creating a starting balance. If an amount is specified here, a grant will be created alongside the entitlement with the specified amount. That grant will have it's rollover settings configured in a way that after each reset operation, the balance will return the original amount specified here.  Manually creating such a grant would mean having the \"amount\", \"minRolloverAmount\", and \"maxRolloverAmount\" fields all be the same. 
 * @param issueAfterResetPriority Defines the grant priority for the default grant. If provided, issueAfterReset must have a value. 
 * @param preserveOverageAtReset If true, the overage is preserved at reset. If false, the usage is forgiven. 
 * @param lastReset The last time usage was reset.
 * @param deletedAt The date and time the resource was deleted.
 */
@Serializable

data class GetEntitlementById (

    /* The feature the subject is entitled to use. Either featureKey or featureId is required.  */
    @SerialName(value = "featureKey") @Required override val featureKey: kotlin.String,

    /* The feature the subject is entitled to use. Either featureKey or featureId is required.  */
    @SerialName(value = "featureId") @Required override val featureId: kotlin.String,

    @SerialName(value = "usagePeriod") @Required override val usagePeriod: RecurringPeriod,

    @SerialName(value = "type") @Required override val type: Entitlement.Type,

    /* The time from which usage is measured. If not specified on creation, defaults to the entitlement creation time.  */
    @SerialName(value = "measureUsageFrom") @Required override val measureUsageFrom: kotlinx.datetime.Instant,

    @SerialName(value = "currentUsagePeriod") @Required override val currentUsagePeriod: Period,

    /* Readonly unique ULID identifier.  */
    @SerialName(value = "id") @Required override val id: kotlin.String,

    /* The date and time the resource was created. */
    @SerialName(value = "createdAt") @Required override val createdAt: kotlinx.datetime.Instant,

    /* The date and time the resource was last updated. The initial value is the same as createdAt. */
    @SerialName(value = "updatedAt") @Required override val updatedAt: kotlinx.datetime.Instant,

    /* The identifier key unique to the subject */
    @SerialName(value = "subjectKey") @Required override val subjectKey: kotlin.String,

    /* The JSON parsable config of the entitlement. This value is also returned when checking entitlement access and it is useful for configuring fine-grained access settings to the feature, implemented in your own system. Has to be an object.  */
    @SerialName(value = "config") @Required override val config: kotlin.String,

    /* Additional metadata for the feature.  */
    @SerialName(value = "metadata") override val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* If softLimit=true the subject can use the feature even if the entitlement is exhausted, hasAccess will always be true.  */
    @SerialName(value = "isSoftLimit") override val isSoftLimit: kotlin.Boolean? = false,

    /* Deprecated, ignored by the backend. Please use isSoftLimit instead; this field will be removed in the future.  */
    @SerialName(value = "isUnlimited") override val isUnlimited: kotlin.Boolean? = false,

    /* You can grant usage automatically alongside the entitlement, the example scenario would be creating a starting balance. If an amount is specified here, a grant will be created alongside the entitlement with the specified amount. That grant will have it's rollover settings configured in a way that after each reset operation, the balance will return the original amount specified here.  Manually creating such a grant would mean having the \"amount\", \"minRolloverAmount\", and \"maxRolloverAmount\" fields all be the same.  */
    @SerialName(value = "issueAfterReset") override val issueAfterReset: kotlin.Double? = null,

    /* Defines the grant priority for the default grant. If provided, issueAfterReset must have a value.  */
    @SerialName(value = "issueAfterResetPriority") override val issueAfterResetPriority: kotlin.Int? = 1,

    /* If true, the overage is preserved at reset. If false, the usage is forgiven.  */
    @SerialName(value = "preserveOverageAtReset") override val preserveOverageAtReset: kotlin.Boolean? = false,

    /* The last time usage was reset. */
    @SerialName(value = "lastReset") override val lastReset: kotlinx.datetime.Instant,

    /* The date and time the resource was deleted. */
    @SerialName(value = "deletedAt") override val deletedAt: kotlinx.datetime.Instant? = null

) : Entitlement {


}

