/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param grantId The id of the grant. 
 * @param usage The usage of the grant. 
 */
@Serializable

data class GrantUsageRecord (

    /* The id of the grant.  */
    @SerialName(value = "grantId") val grantId: kotlin.String? = null,

    /* The usage of the grant.  */
    @SerialName(value = "usage") val usage: kotlin.Double? = null

) {


}

