/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.GrantUsageRecord
import xyz.hisname.openmeter.models.Period

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A segment of the grant burn down history.  A given segment represents the usage of a grant between events that changed either the grant burn down priority order or the usag period. 
 *
 * @param period 
 * @param usage The usage of the grant in the period. 
 * @param overage Overuse that wasn't covered by grants. 
 * @param balanceAtStart The entitlement balance at the start of the period. 
 * @param grantBalancesAtStart The balance breakdown of each active grant at the start of the period: GrantID: Balance 
 * @param balanceAtEnd The entitlement balance at the end of the period. 
 * @param grantBalancesAtEnd The balance breakdown of each active grant at the start of the period: GrantID: Balance 
 * @param grantUsages Which grants were actually burnt down in the period and by what amount. 
 */
@Serializable

data class GrantBurnDownHistorySegment (

    @SerialName(value = "period") val period: Period? = null,

    /* The usage of the grant in the period.  */
    @SerialName(value = "usage") val usage: kotlin.Double? = null,

    /* Overuse that wasn't covered by grants.  */
    @SerialName(value = "overage") val overage: kotlin.Double? = null,

    /* The entitlement balance at the start of the period.  */
    @SerialName(value = "balanceAtStart") val balanceAtStart: kotlin.Double? = null,

    /* The balance breakdown of each active grant at the start of the period: GrantID: Balance  */
    @SerialName(value = "grantBalancesAtStart") val grantBalancesAtStart: kotlin.collections.Map<kotlin.String, kotlin.Double>? = null,

    /* The entitlement balance at the end of the period.  */
    @SerialName(value = "balanceAtEnd") val balanceAtEnd: kotlin.Double? = null,

    /* The balance breakdown of each active grant at the start of the period: GrantID: Balance  */
    @SerialName(value = "grantBalancesAtEnd") val grantBalancesAtEnd: kotlin.collections.Map<kotlin.String, kotlin.Double>? = null,

    /* Which grants were actually burnt down in the period and by what amount.  */
    @SerialName(value = "grantUsages") val grantUsages: kotlin.collections.List<GrantUsageRecord>? = null

) {


}

