/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.Event

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An ingested event with optional validation error.
 *
 * @param event 
 * @param validationError 
 */
@Serializable

data class IngestedEvent (

    @SerialName(value = "event") @Required val event: Event,

    @SerialName(value = "validationError") val validationError: kotlin.String? = null

) {


}

