/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id Invalidate a portal token by ID.
 * @param subject Invalidate all portal tokens for a subject.
 */
@Serializable

data class InvalidatePortalTokensRequest (

    /* Invalidate a portal token by ID. */
    @SerialName(value = "id") val id: kotlin.String? = null,

    /* Invalidate all portal tokens for a subject. */
    @SerialName(value = "subject") val subject: kotlin.String? = null

) {


}

