/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A row in the result of a meter query.
 *
 * @param `value` 
 * @param windowStart 
 * @param windowEnd 
 * @param subject The subject of the meter value.
 * @param groupBy 
 */
@Serializable

data class MeterQueryRow (

    @SerialName(value = "value") @Required val `value`: kotlin.Double,

    @SerialName(value = "windowStart") @Required val windowStart: kotlinx.datetime.Instant,

    @SerialName(value = "windowEnd") @Required val windowEnd: kotlinx.datetime.Instant,

    /* The subject of the meter value. */
    @SerialName(value = "subject") val subject: kotlin.String? = null,

    @SerialName(value = "groupBy") val groupBy: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

