/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.MeterQueryRow
import xyz.hisname.openmeter.models.WindowSize

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The result of a meter query.
 *
 * @param `data` 
 * @param from 
 * @param to 
 * @param windowSize 
 */
@Serializable

data class MeterQueryResult (

    @SerialName(value = "data") @Required val `data`: kotlin.collections.List<MeterQueryRow>,

    @SerialName(value = "from") val from: kotlinx.datetime.Instant? = null,

    @SerialName(value = "to") val to: kotlinx.datetime.Instant? = null,

    @SerialName(value = "windowSize") val windowSize: WindowSize? = null

) {


}

