/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.FeatureMeta
import xyz.hisname.openmeter.models.NotificationChannelMeta
import xyz.hisname.openmeter.models.NotificationEventType
import xyz.hisname.openmeter.models.NotificationRuleBalanceThresholdValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Notification rule for triggering notification events by applying conditions to current balance of entitlements. 
 *
 * @param id A unique identifier for the notification rule.
 * @param type 
 * @param name The user friendly name of the notification rule.
 * @param channels List of notification channels the rule applies to.
 * @param createdAt Timestamp when the rule was created.
 * @param updatedAt Timestamp when the rule was modified.
 * @param disabled Whether the rule is disabled or not.
 * @param thresholds List of thresholds the rule suppose to be triggered.
 * @param deletedAt Timestamp when the channel was deleted.
 * @param features Optional field containing list of features the rule applies to.
 */
@Serializable

data class NotificationRuleBalanceThreshold (

    /* A unique identifier for the notification rule. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "type") @Required val type: NotificationEventType,

    /* The user friendly name of the notification rule. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* List of notification channels the rule applies to. */
    @SerialName(value = "channels") @Required val channels: kotlin.collections.List<NotificationChannelMeta>,

    /* Timestamp when the rule was created. */
    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    /* Timestamp when the rule was modified. */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant,

    /* Whether the rule is disabled or not. */
    @SerialName(value = "disabled") @Required val disabled: kotlin.Boolean = false,

    /* List of thresholds the rule suppose to be triggered. */
    @SerialName(value = "thresholds") @Required val thresholds: kotlin.collections.List<NotificationRuleBalanceThresholdValue>,

    /* Timestamp when the channel was deleted. */
    @SerialName(value = "deletedAt") val deletedAt: kotlinx.datetime.Instant? = null,

    /* Optional field containing list of features the rule applies to. */
    @SerialName(value = "features") val features: kotlin.collections.Set<FeatureMeta>? = null

) {


}

