/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.NotificationChannelType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Common fields for notification channel resources.
 *
 * @param id A unique identifier for the notification channel.
 * @param type 
 * @param name User friendly name of the channel.
 * @param createdAt Timestamp when the channel was created.
 * @param updatedAt Timestamp when the channel was modified.
 * @param disabled Whether the channel is disabled or not.
 * @param deletedAt Timestamp when the channel was deleted.
 */
@Serializable

data class NotificationChannelCommon (

    /* A unique identifier for the notification channel. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "type") @Required val type: NotificationChannelType,

    /* User friendly name of the channel. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Timestamp when the channel was created. */
    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    /* Timestamp when the channel was modified. */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant,

    /* Whether the channel is disabled or not. */
    @SerialName(value = "disabled") @Required val disabled: kotlin.Boolean = false,

    /* Timestamp when the channel was deleted. */
    @SerialName(value = "deletedAt") val deletedAt: kotlinx.datetime.Instant? = null

) {


}

