/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.EntitlementMetered
import xyz.hisname.openmeter.models.EntitlementValue
import xyz.hisname.openmeter.models.Feature
import xyz.hisname.openmeter.models.NotificationRuleBalanceThresholdValue
import xyz.hisname.openmeter.models.Subject

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param entitlement 
 * @param feature 
 * @param subject 
 * @param `value` 
 * @param threshold 
 */
@Serializable

data class NotificationEventBalanceThresholdPayloadAllOfData (

    @SerialName(value = "entitlement") @Required val entitlement: EntitlementMetered,

    @SerialName(value = "feature") @Required val feature: Feature,

    @SerialName(value = "subject") @Required val subject: Subject,

    @SerialName(value = "value") @Required val `value`: EntitlementValue,

    @SerialName(value = "threshold") @Required val threshold: NotificationRuleBalanceThresholdValue

) {


}

