/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.NotificationChannelType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Limited representation of notification channel which includes only the channel identifier and its type. 
 *
 * @param id A unique identifier for the notification channel.
 * @param type 
 */
@Serializable

data class NotificationChannelMeta (

    /* A unique identifier for the notification channel. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "type") @Required val type: NotificationChannelType

) {


}

