/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.NotificationChannelType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name User friendly name of the channel.
 * @param type 
 * @param url Webhook URL where the notification is sent.
 * @param disabled Whether the channel is disabled or not.
 * @param customHeaders Custom HTTP headers sent as part of the webhook request.
 * @param signingSecret Signing secret used for webhook request validation on the receiving end. Automatically generated if not provided.  Format: `base64` encoded random bytes optionally prefixed with `whsec_`. Recommended size: 24 
 */
@Serializable

data class NotificationChannelWebhookCreateRequest (

    /* User friendly name of the channel. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "type") @Required val type: NotificationChannelType,

    /* Webhook URL where the notification is sent. */
    @SerialName(value = "url") @Required val url: kotlin.String,

    /* Whether the channel is disabled or not. */
    @SerialName(value = "disabled") val disabled: kotlin.Boolean? = false,

    /* Custom HTTP headers sent as part of the webhook request. */
    @SerialName(value = "customHeaders") val customHeaders: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Signing secret used for webhook request validation on the receiving end. Automatically generated if not provided.  Format: `base64` encoded random bytes optionally prefixed with `whsec_`. Recommended size: 24  */
    @SerialName(value = "signingSecret") val signingSecret: kotlin.String? = null

) {


}

