/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.NotificationEventBalanceThresholdPayloadAllOfData
import xyz.hisname.openmeter.models.NotificationEventType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Defines payload for notification event which is triggered when the `balance` of the `entitlement` surpass the user defined `threshold`. 
 *
 * @param id A unique identifier for the notification event the payload belongs to.
 * @param type 
 * @param timestamp Timestamp when the notification event was created.
 * @param `data` 
 */
@Serializable

data class NotificationEventBalanceThresholdPayload (

    /* A unique identifier for the notification event the payload belongs to. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "type") @Required val type: NotificationEventType,

    /* Timestamp when the notification event was created. */
    @SerialName(value = "timestamp") @Required val timestamp: kotlinx.datetime.Instant,

    @SerialName(value = "data") @Required val `data`: NotificationEventBalanceThresholdPayloadAllOfData

) {


}

