/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.NotificationChannelType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Common fields for create notification channel request.
 *
 * @param name User friendly name of the channel.
 * @param type 
 * @param disabled Whether the channel is disabled or not.
 */
@Serializable

data class NotificationChannelCommonCreateRequest (

    /* User friendly name of the channel. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "type") @Required val type: NotificationChannelType,

    /* Whether the channel is disabled or not. */
    @SerialName(value = "disabled") val disabled: kotlin.Boolean? = false

) {


}

