/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Threshold value with multiple supported types.
 *
 * @param `value` 
 * @param type 
 */
@Serializable

data class NotificationRuleBalanceThresholdValue (

    @SerialName(value = "value") @Required val `value`: kotlin.Double,

    @SerialName(value = "type") @Required val type: NotificationRuleBalanceThresholdValue.Type

) {

    /**
     * 
     *
     * Values: NUMBER,PERCENT
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "NUMBER") NUMBER("NUMBER"),
        @SerialName(value = "PERCENT") PERCENT("PERCENT");
    }

}

