/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.NotificationEventType
import xyz.hisname.openmeter.models.NotificationRuleBalanceThresholdValue

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Request for creating new notification rule for triggering notification events base on conditions applied to current balance of entitlements. 
 *
 * @param type 
 * @param name The user friendly name of the notification rule.
 * @param channels List of notification channel identifiers or names the rule applies to.
 * @param thresholds List of thresholds the rule suppose to be triggered.
 * @param disabled Whether the rule is disabled or not.
 * @param features Optional field for defining the scope of notification by feature. It may contain features by id or key. 
 */
@Serializable

data class NotificationRuleBalanceThresholdCreateRequest (

    @SerialName(value = "type") @Required val type: NotificationEventType,

    /* The user friendly name of the notification rule. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* List of notification channel identifiers or names the rule applies to. */
    @SerialName(value = "channels") @Required val channels: kotlin.collections.List<kotlin.String>,

    /* List of thresholds the rule suppose to be triggered. */
    @SerialName(value = "thresholds") @Required val thresholds: kotlin.collections.List<NotificationRuleBalanceThresholdValue>,

    /* Whether the rule is disabled or not. */
    @SerialName(value = "disabled") val disabled: kotlin.Boolean? = false,

    /* Optional field for defining the scope of notification by feature. It may contain features by id or key.  */
    @SerialName(value = "features") val features: kotlin.collections.Set<kotlin.String>? = null

) {


}

