/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.NotificationChannelType
import xyz.hisname.openmeter.models.NotificationChannelWebhook

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param id A unique identifier for the notification channel.
 * @param type 
 * @param name User friendly name of the channel.
 * @param createdAt Timestamp when the channel was created.
 * @param updatedAt Timestamp when the channel was modified.
 * @param disabled Whether the channel is disabled or not.
 * @param url Webhook URL where the notification is sent.
 * @param signingSecret Signing secret used for webhook request validation on the receiving end.  Format: `base64` encoded random bytes optionally prefixed with `whsec_`. Recommended size: 24 
 * @param deletedAt Timestamp when the channel was deleted.
 * @param customHeaders Custom HTTP headers sent as part of the webhook request.
 */
@Serializable

sealed interface NotificationChannel {

    /* A unique identifier for the notification channel. */
    @SerialName(value = "id") @Required val id: kotlin.String
    @SerialName(value = "type") @Required val type: NotificationChannelType
    /* User friendly name of the channel. */
    @SerialName(value = "name") @Required val name: kotlin.String
    /* Timestamp when the channel was created. */
    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant
    /* Timestamp when the channel was modified. */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant
    /* Whether the channel is disabled or not. */
    @SerialName(value = "disabled") @Required val disabled: kotlin.Boolean
    /* Webhook URL where the notification is sent. */
    @SerialName(value = "url") @Required val url: kotlin.String
    /* Signing secret used for webhook request validation on the receiving end.  Format: `base64` encoded random bytes optionally prefixed with `whsec_`. Recommended size: 24  */
    @SerialName(value = "signingSecret") @Required val signingSecret: kotlin.String
    /* Timestamp when the channel was deleted. */
    @SerialName(value = "deletedAt") val deletedAt: kotlinx.datetime.Instant?
    /* Custom HTTP headers sent as part of the webhook request. */
    @SerialName(value = "customHeaders") val customHeaders: kotlin.collections.Map<kotlin.String, kotlin.Any>?

}

