/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.NotificationEventPayload
import xyz.hisname.openmeter.models.NotificationEventType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Request for creating new notification event with specific type and payload. 
 *
 * @param type 
 * @param payload 
 * @param ruleId 
 */
@Serializable

data class NotificationEventCreateRequest (

    @SerialName(value = "type") @Required val type: NotificationEventType,

    @SerialName(value = "payload") @Required val payload: NotificationEventPayload,

    @SerialName(value = "ruleId") @Required val ruleId: kotlin.String

) {


}

