/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.NotificationEventType

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Defines the common fields of a notification rule.
 *
 * @param id A unique identifier for the notification rule.
 * @param type 
 */
@Serializable

data class NotificationRuleMeta (

    /* A unique identifier for the notification rule. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "type") @Required val type: NotificationEventType

) {


}

