/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.NotificationChannel

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param totalCount Total number of channels.
 * @param page Current page number.
 * @param pageSize Number of channels per page.
 * @param items List of channels.
 */
@Serializable

data class NotificationChannelsResponse (

    /* Total number of channels. */
    @SerialName(value = "totalCount") @Required val totalCount: kotlin.Int,

    /* Current page number. */
    @SerialName(value = "page") @Required val page: kotlin.Int,

    /* Number of channels per page. */
    @SerialName(value = "pageSize") @Required val pageSize: kotlin.Int,

    /* List of channels. */
    @SerialName(value = "items") @Required val items: kotlin.collections.List<NotificationChannel>

) {


}

