/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.NotificationEventDeliveryStatus
import xyz.hisname.openmeter.models.NotificationEventPayload
import xyz.hisname.openmeter.models.NotificationEventType
import xyz.hisname.openmeter.models.NotificationRule

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Notification event generated by the system based on the criteria defined in the corresponding a notification rule.  The `payload` field contains the actual message sent to the notification channel. 
 *
 * @param id A unique identifier for the notification event.
 * @param type 
 * @param createdAt Timestamp when the notification event was created.
 * @param rule 
 * @param deliveryStatus The delivery status of the notification event.
 * @param payload 
 * @param annotations List of annotations managed by the system. 
 */
@Serializable

data class NotificationEvent (

    /* A unique identifier for the notification event. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "type") @Required val type: NotificationEventType,

    /* Timestamp when the notification event was created. */
    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "rule") @Required val rule: NotificationRule,

    /* The delivery status of the notification event. */
    @SerialName(value = "deliveryStatus") @Required val deliveryStatus: kotlin.collections.List<NotificationEventDeliveryStatus>,

    @SerialName(value = "payload") @Required val payload: NotificationEventPayload,

    /* List of annotations managed by the system.  */
    @SerialName(value = "annotations") val annotations: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

