/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models


import kotlinx.serialization.*

/**
 * The type of the notification event.
 *
 * Values: entitlementsPeriodBalancePeriodThreshold
 */
@Serializable
enum class NotificationEventType(val value: kotlin.String) {

    @SerialName(value = "entitlements.balance.threshold")
    entitlementsPeriodBalancePeriodThreshold("entitlements.balance.threshold");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is NotificationEventType) "$data" else null

        /**
         * Returns a valid [NotificationEventType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): NotificationEventType? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

