/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A time period 
 *
 * @param from Period start time where the amount was applied. If applicable. 
 * @param to Period end time where the amount was applied. If applicable. 
 */
@Serializable

data class Period (

    /* Period start time where the amount was applied. If applicable.  */
    @SerialName(value = "from") @Required val from: kotlinx.datetime.Instant,

    /* Period end time where the amount was applied. If applicable.  */
    @SerialName(value = "to") @Required val to: kotlinx.datetime.Instant

) {


}

