/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A consumer portal token.
 *
 * @param subject 
 * @param id 
 * @param expiresAt 
 * @param expired 
 * @param createdAt 
 * @param token The token is only returned at creation.
 * @param allowedMeterSlugs Optional, if defined only the specified meters will be allowed
 */
@Serializable

data class PortalToken (

    @SerialName(value = "subject") @Required val subject: kotlin.String,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "expiresAt") val expiresAt: kotlinx.datetime.Instant? = null,

    @SerialName(value = "expired") val expired: kotlin.Boolean? = null,

    @SerialName(value = "createdAt") val createdAt: kotlinx.datetime.Instant? = null,

    /* The token is only returned at creation. */
    @SerialName(value = "token") val token: kotlin.String? = null,

    /* Optional, if defined only the specified meters will be allowed */
    @SerialName(value = "allowedMeterSlugs") val allowedMeterSlugs: kotlin.collections.Set<kotlin.String>? = null

) {


}

