/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models


import kotlinx.serialization.*

/**
 * List of pre-defined periods that can be used for recurring & scheduling.  DAY:      Every day WEEK:     Every week MONTH:    Every month YEAR:     Every year 
 *
 * Values: DAY,WEEK,MONTH,YEAR
 */
@Serializable
enum class RecurringPeriodEnum(val value: kotlin.String) {

    @SerialName(value = "DAY")
    DAY("DAY"),

    @SerialName(value = "WEEK")
    WEEK("WEEK"),

    @SerialName(value = "MONTH")
    MONTH("MONTH"),

    @SerialName(value = "YEAR")
    YEAR("YEAR");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is RecurringPeriodEnum) "$data" else null

        /**
         * Returns a valid [RecurringPeriodEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): RecurringPeriodEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

