/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.RecurringPeriodEnum

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Recurring period of an entitlement. 
 *
 * @param interval 
 * @param anchor An arbitrary anchor to base the recurring period on. 
 */
@Serializable

data class RecurringPeriod (

    @SerialName(value = "interval") @Required val interval: RecurringPeriodEnum,

    /* An arbitrary anchor to base the recurring period on.  */
    @SerialName(value = "anchor") @Required val anchor: kotlinx.datetime.Instant

) {


}

