/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A subject is a unique identifier for a user or entity.
 *
 * @param key 
 * @param id 
 * @param displayName 
 * @param metadata 
 * @param currentPeriodStart 
 * @param currentPeriodEnd 
 * @param stripeCustomerId 
 */
@Serializable

data class Subject (

    @SerialName(value = "key") @Required val key: kotlin.String,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "displayName") val displayName: kotlin.String? = null,

    @SerialName(value = "metadata") val metadata: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    @SerialName(value = "currentPeriodStart") val currentPeriodStart: kotlinx.datetime.Instant? = null,

    @SerialName(value = "currentPeriodEnd") val currentPeriodEnd: kotlinx.datetime.Instant? = null,

    @SerialName(value = "stripeCustomerId") val stripeCustomerId: kotlin.String? = null

) {


}

