/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param type 
 * @param `data` 
 */
@Serializable

data class SvixOperationalWebhookRequest (

    @SerialName(value = "type") @Required val type: SvixOperationalWebhookRequest.Type,

    @SerialName(value = "data") @Required val `data`: kotlin.collections.Map<kotlin.String, kotlin.String>

) {

    /**
     * 
     *
     * Values: endpointPeriodCreated,endpointPeriodDeleted,endpointPeriodDisabled,endpointPeriodUpdated,messagePeriodAttemptPeriodExhausted,messagePeriodAttemptPeriodFailing,messagePeriodAttemptPeriodRecovered
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "endpoint.created") endpointPeriodCreated("endpoint.created"),
        @SerialName(value = "endpoint.deleted") endpointPeriodDeleted("endpoint.deleted"),
        @SerialName(value = "endpoint.disabled") endpointPeriodDisabled("endpoint.disabled"),
        @SerialName(value = "endpoint.updated") endpointPeriodUpdated("endpoint.updated"),
        @SerialName(value = "message.attempt.exhausted") messagePeriodAttemptPeriodExhausted("message.attempt.exhausted"),
        @SerialName(value = "message.attempt.failing") messagePeriodAttemptPeriodFailing("message.attempt.failing"),
        @SerialName(value = "message.attempt.recovered") messagePeriodAttemptPeriodRecovered("message.attempt.recovered");
    }

}

