/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package xyz.hisname.openmeter.models

import xyz.hisname.openmeter.models.BalanceHistoryWindow
import xyz.hisname.openmeter.models.GrantBurnDownHistorySegment

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The windowed balance history. 
 *
 * @param windowedHistory The windowed balance history. - It only returns rows for windows where there was usage. - The windows are inclusive at their start and exclusive at their end. - The last window may be smaller than the window size and is inclusive at both ends. 
 * @param burndownHistory Grant burndown history. 
 */
@Serializable

data class WindowedBalanceHistory (

    /* The windowed balance history. - It only returns rows for windows where there was usage. - The windows are inclusive at their start and exclusive at their end. - The last window may be smaller than the window size and is inclusive at both ends.  */
    @SerialName(value = "windowedHistory") val windowedHistory: kotlin.collections.List<BalanceHistoryWindow>? = null,

    /* Grant burndown history.  */
    @SerialName(value = "burndownHistory") val burndownHistory: kotlin.collections.List<GrantBurnDownHistorySegment>? = null

) {


}

